//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.04 at 02:47:52 PM CEST 
//


package un.unece.uncefact.data.standard.reusableaggregatebusinessinformationentity._12;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the un.unece.uncefact.data.standard.reusableaggregatebusinessinformationentity._12 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: un.unece.uncefact.data.standard.reusableaggregatebusinessinformationentity._12
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LogisticsServiceChargeType }
     * 
     */
    public LogisticsServiceChargeType createLogisticsServiceChargeType() {
        return new LogisticsServiceChargeType();
    }

    /**
     * Create an instance of {@link SupplyChainTradeDeliveryType }
     * 
     */
    public SupplyChainTradeDeliveryType createSupplyChainTradeDeliveryType() {
        return new SupplyChainTradeDeliveryType();
    }

    /**
     * Create an instance of {@link TradePriceType }
     * 
     */
    public TradePriceType createTradePriceType() {
        return new TradePriceType();
    }

    /**
     * Create an instance of {@link TradeProductType }
     * 
     */
    public TradeProductType createTradeProductType() {
        return new TradeProductType();
    }

    /**
     * Create an instance of {@link SupplyChainTradeLineItemType }
     * 
     */
    public SupplyChainTradeLineItemType createSupplyChainTradeLineItemType() {
        return new SupplyChainTradeLineItemType();
    }

    /**
     * Create an instance of {@link TradePaymentTermsType }
     * 
     */
    public TradePaymentTermsType createTradePaymentTermsType() {
        return new TradePaymentTermsType();
    }

    /**
     * Create an instance of {@link TradeSettlementMonetarySummationType }
     * 
     */
    public TradeSettlementMonetarySummationType createTradeSettlementMonetarySummationType() {
        return new TradeSettlementMonetarySummationType();
    }

    /**
     * Create an instance of {@link SupplyChainTradeAgreementType }
     * 
     */
    public SupplyChainTradeAgreementType createSupplyChainTradeAgreementType() {
        return new SupplyChainTradeAgreementType();
    }

    /**
     * Create an instance of {@link TaxRegistrationType }
     * 
     */
    public TaxRegistrationType createTaxRegistrationType() {
        return new TaxRegistrationType();
    }

    /**
     * Create an instance of {@link ExchangedDocumentContextType }
     * 
     */
    public ExchangedDocumentContextType createExchangedDocumentContextType() {
        return new ExchangedDocumentContextType();
    }

    /**
     * Create an instance of {@link TradeCountryType }
     * 
     */
    public TradeCountryType createTradeCountryType() {
        return new TradeCountryType();
    }

    /**
     * Create an instance of {@link TradeAllowanceChargeType }
     * 
     */
    public TradeAllowanceChargeType createTradeAllowanceChargeType() {
        return new TradeAllowanceChargeType();
    }

    /**
     * Create an instance of {@link TradeDeliveryTermsType }
     * 
     */
    public TradeDeliveryTermsType createTradeDeliveryTermsType() {
        return new TradeDeliveryTermsType();
    }

    /**
     * Create an instance of {@link UniversalCommunicationType }
     * 
     */
    public UniversalCommunicationType createUniversalCommunicationType() {
        return new UniversalCommunicationType();
    }

    /**
     * Create an instance of {@link SupplyChainTradeSettlementType }
     * 
     */
    public SupplyChainTradeSettlementType createSupplyChainTradeSettlementType() {
        return new SupplyChainTradeSettlementType();
    }

    /**
     * Create an instance of {@link TradeAddressType }
     * 
     */
    public TradeAddressType createTradeAddressType() {
        return new TradeAddressType();
    }

    /**
     * Create an instance of {@link SupplyChainConsignmentType }
     * 
     */
    public SupplyChainConsignmentType createSupplyChainConsignmentType() {
        return new SupplyChainConsignmentType();
    }

    /**
     * Create an instance of {@link DebtorFinancialInstitutionType }
     * 
     */
    public DebtorFinancialInstitutionType createDebtorFinancialInstitutionType() {
        return new DebtorFinancialInstitutionType();
    }

    /**
     * Create an instance of {@link SupplyChainTradeTransactionType }
     * 
     */
    public SupplyChainTradeTransactionType createSupplyChainTradeTransactionType() {
        return new SupplyChainTradeTransactionType();
    }

    /**
     * Create an instance of {@link SupplyChainEventType }
     * 
     */
    public SupplyChainEventType createSupplyChainEventType() {
        return new SupplyChainEventType();
    }

    /**
     * Create an instance of {@link TradePartyType }
     * 
     */
    public TradePartyType createTradePartyType() {
        return new TradePartyType();
    }

    /**
     * Create an instance of {@link ProductClassificationType }
     * 
     */
    public ProductClassificationType createProductClassificationType() {
        return new ProductClassificationType();
    }

    /**
     * Create an instance of {@link LogisticsTransportMovementType }
     * 
     */
    public LogisticsTransportMovementType createLogisticsTransportMovementType() {
        return new LogisticsTransportMovementType();
    }

    /**
     * Create an instance of {@link TradePaymentPenaltyTermsType }
     * 
     */
    public TradePaymentPenaltyTermsType createTradePaymentPenaltyTermsType() {
        return new TradePaymentPenaltyTermsType();
    }

    /**
     * Create an instance of {@link CreditorFinancialAccountType }
     * 
     */
    public CreditorFinancialAccountType createCreditorFinancialAccountType() {
        return new CreditorFinancialAccountType();
    }

    /**
     * Create an instance of {@link TradeContactType }
     * 
     */
    public TradeContactType createTradeContactType() {
        return new TradeContactType();
    }

    /**
     * Create an instance of {@link ExchangedDocumentType }
     * 
     */
    public ExchangedDocumentType createExchangedDocumentType() {
        return new ExchangedDocumentType();
    }

    /**
     * Create an instance of {@link ReferencedProductType }
     * 
     */
    public ReferencedProductType createReferencedProductType() {
        return new ReferencedProductType();
    }

    /**
     * Create an instance of {@link TradeAccountingAccountType }
     * 
     */
    public TradeAccountingAccountType createTradeAccountingAccountType() {
        return new TradeAccountingAccountType();
    }

    /**
     * Create an instance of {@link TradeSettlementPaymentMeansType }
     * 
     */
    public TradeSettlementPaymentMeansType createTradeSettlementPaymentMeansType() {
        return new TradeSettlementPaymentMeansType();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link SpecifiedPeriodType }
     * 
     */
    public SpecifiedPeriodType createSpecifiedPeriodType() {
        return new SpecifiedPeriodType();
    }

    /**
     * Create an instance of {@link DebtorFinancialAccountType }
     * 
     */
    public DebtorFinancialAccountType createDebtorFinancialAccountType() {
        return new DebtorFinancialAccountType();
    }

    /**
     * Create an instance of {@link DocumentContextParameterType }
     * 
     */
    public DocumentContextParameterType createDocumentContextParameterType() {
        return new DocumentContextParameterType();
    }

    /**
     * Create an instance of {@link CreditorFinancialInstitutionType }
     * 
     */
    public CreditorFinancialInstitutionType createCreditorFinancialInstitutionType() {
        return new CreditorFinancialInstitutionType();
    }

    /**
     * Create an instance of {@link TradeTaxType }
     * 
     */
    public TradeTaxType createTradeTaxType() {
        return new TradeTaxType();
    }

    /**
     * Create an instance of {@link DocumentLineDocumentType }
     * 
     */
    public DocumentLineDocumentType createDocumentLineDocumentType() {
        return new DocumentLineDocumentType();
    }

    /**
     * Create an instance of {@link ReferencedDocumentType }
     * 
     */
    public ReferencedDocumentType createReferencedDocumentType() {
        return new ReferencedDocumentType();
    }

    /**
     * Create an instance of {@link ProductCharacteristicType }
     * 
     */
    public ProductCharacteristicType createProductCharacteristicType() {
        return new ProductCharacteristicType();
    }

    /**
     * Create an instance of {@link TradePaymentDiscountTermsType }
     * 
     */
    public TradePaymentDiscountTermsType createTradePaymentDiscountTermsType() {
        return new TradePaymentDiscountTermsType();
    }

}
