//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.04 at 02:47:52 PM CEST 
//


package ferd.crossindustrydocument.invoice._1p0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ferd.crossindustrydocument.invoice._1p0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CrossIndustryDocument_QNAME = new QName("urn:ferd:CrossIndustryDocument:invoice:1p0", "CrossIndustryDocument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ferd.crossindustrydocument.invoice._1p0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CrossIndustryDocumentType }
     * 
     */
    public CrossIndustryDocumentType createCrossIndustryDocumentType() {
        return new CrossIndustryDocumentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrossIndustryDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ferd:CrossIndustryDocument:invoice:1p0", name = "CrossIndustryDocument")
    public JAXBElement<CrossIndustryDocumentType> createCrossIndustryDocument(CrossIndustryDocumentType value) {
        return new JAXBElement<CrossIndustryDocumentType>(_CrossIndustryDocument_QNAME, CrossIndustryDocumentType.class, null, value);
    }

}
